// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBudeIe3_6AG6FERkkOGrxWs76RYVetdsU',
    appId: '1:243206602501:web:6e79ad0f392c0e511c416c',
    messagingSenderId: '243206602501',
    projectId: 'atelier-4-z-naciri-iir5g7',
    authDomain: 'atelier-4-z-naciri-iir5g7.firebaseapp.com',
    storageBucket: 'atelier-4-z-naciri-iir5g7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qFg-sLA6L0Nt9hsF4xIKeZtFjcsrEKc',
    appId: '1:243206602501:android:01727d530f451e9e1c416c',
    messagingSenderId: '243206602501',
    projectId: 'atelier-4-z-naciri-iir5g7',
    storageBucket: 'atelier-4-z-naciri-iir5g7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFSr-bVsCq7AiIe0Ib7y3UtGOAOp9AnQA',
    appId: '1:243206602501:ios:1d428adb5b9309a81c416c',
    messagingSenderId: '243206602501',
    projectId: 'atelier-4-z-naciri-iir5g7',
    storageBucket: 'atelier-4-z-naciri-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFSr-bVsCq7AiIe0Ib7y3UtGOAOp9AnQA',
    appId: '1:243206602501:ios:b4e0b748dc85474a1c416c',
    messagingSenderId: '243206602501',
    projectId: 'atelier-4-z-naciri-iir5g7',
    storageBucket: 'atelier-4-z-naciri-iir5g7.appspot.com',
    iosBundleId: 'com.example.atelier4.RunnerTests',
  );
}
